---
driver:
  name: docker

driver_config:
  use_sudo: false
  privileged: true
  provision_command: mkdir -p /run/sshd
  run_command: /lib/systemd/systemd

platforms:
  - name: debian-9
    driver_config:
      provision_command:
        - apt-get install udev net-tools -y
  - name: ubuntu-18.04
    driver_config:
      provision_command:
        - apt-get install udev net-tools -y
  - name: centos-7
    driver_config:
      provision_command:
        - yum install udev net-tools -y

provisioner:
  name: salt_solo
  log_level: info
  require_chef: false
  salt_version: latest
  formula: salt
  salt_copy_filter:
    - .kitchen
    - .git
  pillars:
    top.sls:
      base:
        '*':
          - salt
    salt.sls:
      salt:
        master:
          fileserver_backend:
            - rootfs
          file_roots:
            base:
              - /srv/salt
          pillar_roots:
            base:
              - /srv/pillar
        minion:
          master: localhost
          fileserver_backend:
            - rootfs
          file_roots:
            base:
              - /srv/salt
          pillar_roots:
            base:
              - /srv/pillar

verifier:
  name: inspec
  sudo: true
  reporter:
    - cli
  inspec_tests:
    - path: test/integration/default

suites:
  - name: salt
    provisioner:
      state_top:
        base:
          '*':
            - salt.master
            - salt.minion
